Add build scripts for packaging tendrl-monitoring-integration
rishubhjain/monitoring-integration pull request #2
Opened 2017-08-02 07:45 UTC by TimothyAsirJeyasing

Signed-off-by: Timothy Asir J <tjeyasin@redhat.com>

2017-08-02 07:46 UTC, TimothyAsirJeyasing commented
@r0h4n , @nthomas-redhat , @mbukatov , @dahorak,  @rishubhjain , Please review

2017-08-02 07:48 UTC, TimothyAsirJeyasing commented
https://github.com/Tendrl/specifications/issues/178

2017-08-02 17:23 UTC, cybernth requested changes

2017-08-02 17:23 UTC, cybernth commented on tendrl-monitoring-integration.spec
> +Requires: grafana
Requires:
graphite-web
python-carbon 
python-whisper

2017-08-02 17:23 UTC, nthomas-redhat commented on tendrl-monitoring-integration.spec
> +install -Dm 0644 graphite.conf.sample.yml $RPM_BUILD_ROOT%{_sysconfdir}/tendrl/monitoring_integration/graphite.conf.yml
Note that these config files might be required here:

https://github.com/Tendrl/performance-monitoring/blob/master/etc/tendrl/performance-monitoring/graphite-web.conf.sample

https://github.com/Tendrl/performance-monitoring/blob/master/etc/tendrl/performance-monitoring/carbon.conf.sample

stay tuned to https://github.com/Tendrl/monitoring-integration/pull/1

2017-08-02 17:23 UTC, nthomas-redhat commented on tendrl-monitoring-integration.spec
> +%preun
Same as above. refer https://github.com/Tendrl/performance-monitoring/blob/master/tendrl-performance-monitoring.spec

2017-08-02 17:23 UTC, nthomas-redhat commented on tendrl-monitoring-integration.spec
> +%postun
same as above

2017-08-04 11:27 UTC, mbukatov commented
I guess that this could be closed, as I see the rpm spec file included in master branch of Tendrl/monitoring-integration, right?

2017-08-10 05:47 UTC, closed without merging